<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <div class="panel-group" id="listaSolucoes" role="tablist" aria-multiselecttable="true">
            <div class="panel panel-default panel-custom">
                <div class="panel-heading" role="tab" id="tab1">
                    <h4 class="panel-title">
                        <a role="button" data-toggle="collapse" data-parent="#listaSolucoes" href="#ecommerce" aria-expended="false" aria-controls="ecommerce">
                            E-commerce
                        </a>
                    </h4>
                </div>
                <div id="ecommerce" class="panel-collapse collapse out" role="tabpanel" aria-labelledby="tab1">
                    <div class="panel-body">
                        Solução voltada para o comércio eletronico, podendo ter integração com qualquer sistema de gestão (ERP)
                    </div>
                </div>
            </div>
            <div class="panel panel-default panel-custom">
                <div class="panel-heading" role="tab" id="tab2">
                    <h4 class="panel-title">
                        <a role="button" data-toggle="collapse" data-parent="#listaSolucoes" href="#institucional" aria-expended="false" aria-controls="institucional">
                            Site Institucional
                        </a>
                    </h4>
                </div>
                <div id="institucional" class="panel-collapse collapse out" role="tabpanel" aria-labelledby="tab2">
                    <div class="panel-body">
                        Solução voltada para o comércio eletronico, podendo ter integração com qualquer sistema de gestão (ERP)
                    </div>
                </div>
            </div>
            <div class="panel panel-default panel-custom">
                <div class="panel-heading" role="tab" id="tab3">
                    <h4 class="panel-title">
                        <a role="button" data-toggle="collapse" data-parent="#listaSolucoes" href="#gerenciamentoConteudo" aria-expended="false" aria-controls="gerenciamentoConteudo">
                            Blog
                        </a>
                    </h4>
                </div>
                <div id="gerenciamentoConteudo" class="panel-collapse collapse out" role="tabpanel" aria-labelledby="tab3">
                    <div class="panel-body">
                        Solução voltada para o comércio eletronico, podendo ter integração com qualquer sistema de gestão (ERP)
                    </div>
                </div>
            </div>
            <div class="panel panel-default panel-custom">
                <div class="panel-heading" role="tab" id="tab4">
                    <h4 class="panel-title">
                        <a role="button" data-toggle="collapse" data-parent="#listaSolucoes" href="#web" aria-expended="false" aria-controls="ecommerce">
                            Sistema Web
                        </a>
                    </h4>
                </div>
                <div id="web" class="panel-collapse collapse out" role="tabpanel" aria-labelledby="tab4">
                    <div class="panel-body">
                        Solução voltada para o comércio eletronico, podendo ter integração com qualquer sistema de gestão (ERP)
                    </div>
                </div>
            </div>
            
        </div>
        
    </div>    
</div>