<div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
        
        <ul class="nav nav-tabs" role="tablist">
            <li id="Tabs" class="active" role="presentation">
                <a href="#objetivo" aria-controls="objetivo" role="tab" data-toggle="tab">
                    Missão
                </a>   
            </li>
            <li id="Tabs" role="presentation">
                <a href="#visao" aria-controls="visao" role="tab" data-toggle="tab">
                    Visão
                </a>   
            </li>
            <li id="Tabs" role="presentation">
                <a href="#missao" aria-controls="missao" role="tab" data-toggle="tab">
                    Valores
                </a>   
            </li>
<!--            <li id="Tabs" role="presentation">
                <a href="#capacity" aria-controls="capacity" role="tab" data-toggle="tab">
                    Competências Técnicas
                </a>   
            </li>-->
        </ul>
        <div class="tab-content">
            <div id="objetivo" role="tabpanel" class="tab-pane active identacao">
                Entregar um produto com valor a sua empresa, focando em soluções de qualidade, adaptadas ao seu negócio e principal com um custo acessível.
            </div>
            <div id="visao"  role="tabpanel" class="tab-pane fade identacao">
                Ser reconhecido pelos clientes como sinônimo de qualidade.
            </div>
            <div id="missao"  role="tabpanel" class="tab-pane fade identacao">
                Colocar-se no lugar para melhor entendimento do negócio e da cultura de sua empresa e ser transparênte em todas as informações transmitidas.
            </div>
<!--            <div id="capacity"  role="tabpanel" class="tab-pane fade ">
                <p>
                    <label>
                            HTML 5
                    </label><br/>
                    <div class="progress">

                         <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:70%">
                             7
                        </div>
                    </div>
                </p>
                
                <p>
                    <label>
                            Javascipt
                    </label><br/>
                    <div class="progress">

                         <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:70%">
                             8
                        </div>
                    </div>
                </p>
                
                <p>
                    <label>
                            CSS3
                    </label><br/>
                    <div class="progress">

                         <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:60%">
                             6
                        </div>
                    </div>
                </p>
                <p>
                    <label>
                            PHP
                    </label><br/>
                    <div class="progress">

                         <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:70%">
                             7
                        </div>
                    </div>
                </p>
                 <p>
                    <label>
                            AngularJS
                    </label><br/>
                    <div class="progress">

                         <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:50%">
                             5
                        </div>
                    </div>
                </p>
                 <p>
                    <label>
                            Bootstrap
                    </label><br/>
                    <div class="progress">

                         <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:50%">
                             6
                        </div>
                    </div>
                </p>
                <p>
                    <label>
                            MySQL
                    </label><br/>
                    <div class="progress">

                         <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width:50%">
                             6
                        </div>
                    </div>
                </p>
                
            </div>-->
        </div>
    </div>
</div>