<!--<div class="row" style="margin-bottom:5%;">
    <div clas="col-xs-12 col-md-8 col-md-offset-2">
        <div id="carousel-img" class="carousel slide " data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-img" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-img" data-slide-to="1"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img class="img-responsive" src="view/images/ID-10075808.jpg"/>
                </div>
                <div class="item">
                    <img  class="img-responsive" src="view/images/ID-10071997.jpg">
                </div>
            </div>
        </div> 
    </div>
</div>-->
<div class="row">
    
    <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-1">
        <div class="thumbnail">
           <img  class="img-thumbnail" src="view/images/ID-100332309.jpg"/>
            <div class="caption">
              <h3>Sobre</h3>
              <p>
                Consultoria voltada ao que o cliente necessita: Produto com qualidade, adequada ao seu negócio e com um custo acessível... 
                </p>
              <p><a href="Home/About" class="btn btn-primary" role="button">Mais</a></p>
            </div>
        </div>
    </div>
    <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-2">
        <div class="thumbnail">
            <table >
              <tr>
                <td>
                  <img class="img-thumbnail" src="view/images/ID-10072535.jpg"/>
                </td>
                <td>
                  <img class="img-thumbnail" src="view/images/ID-100147793.jpg"/>
                </td>
              </tr>
              <tr>
                <td>
                  <img class="img-thumbnail" src="view/images/ID-100304304.jpg"/>
                </td>
                <td>
                  <img class="img-thumbnail" src="view/images/ID-10044871.jpg"/>
                </td>
              </tr>
            </table>
            <div class="caption">
              <h3>Soluções</h3>
              <p>Hoje em dia ser tecnologicamente ativo é estar na frente de milhares de pessoas, porém é necessario saber usar também em benefício de sua compania.</p>
              <p><a href="#" class="btn btn-primary" role="button">Mais</a></p>
            </div>
        </div>
    </div>
    
</div>